### ISSUE TITLE
Визуально отделить пользователей разных сообществ - два вида иконок

### ISSUE THREAD

**Issue by juliamayaorlova** [sunsurfers/travelcombot#12]
Я захожу в карту пользователем Сансерфер - вижу свое имя на карте цвета Сансерфер
Я захожу в карту пользователем Сменщик - вижу свое имя на карте цвета Сменщик

**Comment by Fomchenkov** [comment]
Обновлены иконки разных сообществ

Сансёрферы - рокета
Сменщики - коктейль

**Comment by nemelnikov** [comment]
Вячеслав, а в прошлой версии бота у нас рядом с иконкой выводилось ещё имя и фамилия.
Это сложно добавить? мне кажется так удобнее было бы.
