### ISSUE TITLE
Лишний шаг при просмотре карты

### ISSUE THREAD

**Issue by nemelnikov** [sunsurfers/travelcombot#5]
Шаги
- Пользователь подтверждён
- Жмём "Посмотреть геолокации пользователь"

ER: сразу генерируется ссылка
FR: шаг "Какую карту вы хотите посмотреть"

**Comment by Fomchenkov** [comment]
Убран шаг «Какую карту вы хотите посмотреть». 

Сразу генерируется ссылка после нажатия на «Посмотреть геолокацию пользователей».
