### ISSUE TITLE
У сменщиков не запрашивает 3х людей

### ISSUE THREAD

**Issue by nemelnikov** [sunsurfers/travelcombot#7]
Шаги
- Новый пользователь
- Выбираем в сообществе "Смена"

ER: бот запрашивает 3х людей, кто может подтвердить
FR: сразу отправляется заявка

**Comment by Fomchenkov** [comment]
Исправлено. 
У участников сообщества "Смена" запрашиваются имена 3х людей, кто может подтвердить.

**Comment by juliamayaorlova** [comment]
Проверено
